version: '3'
services:
    nginx:
      image: nginx:latest
      container_name: nginx_dcl
      ports:
        - "80:8000"
      volumes:
        - ./src:/src
        - ./config/nginx:/etc/nginx/conf.d
      depends_on:
        - web
    
    web:
      build:  .
      container_name: django_dcl
      command: bash -c "gunicorn kerberos.wsgi -b 0.0.0.0:8000 --workers 3"
      volumes:
        - ./src:/src
      expose:
        - "8000"
